const Databank = {
    restaurantCategories: [
        "Restaurant",
        "Cafe / Coffee Shop",
        "Ice Cream Parlour",
        "Juice Center",
        "Bakery",
        "Fast Food Center",
        "Food Truck",
        "Sweet Shop / Mithai Store",
        "Dessert Bar",
        "Snack Bar / Chaat Corner",
        "Biryani House",
        "Chinese Corner",
        "Tiffin Center",
        "Mess / Homely Meals",
        "Bar / Pub",
        "Lounge",
        "Dhaba",
        "Multi-Cuisine Restaurant",
        "Fine Dining Restaurant",
        "Family Restaurant",
        "Veg Restaurant",
        "Non-Veg Restaurant",
        "Seafood Restaurant",
        "Grill / BBQ Outlet",
        "Pizza Outlet",
        "Burger Joint",
        "Sandwich / Sub Shop",
        "Shawarma Stall",
        "Rolls / Wraps Outlet",
        "Thali Restaurant",
        "South Indian Tiffin",
        "North Indian Diner",
        "Pan Shop / Mukhwas Stall",
        "Organic Food Cafe",
        "Health Food Joint",
        "Cloud Kitchen (Delivery Only)"
    ],
    amenitiesList: [
        "Wi-Fi",
        "Parking",
        "Kids Menu",
        "High Chairs",
        "Outdoor Seating",
        "Indoor Seating",
        "Reservations",
        "Takeaway",
        "Delivery",
        "Wheelchair Accessible",
        "Restroom Facilities",
        "TV",
        "Live Music",
        "Outdoor Dining",
        "Pet Friendly",
        "Smoking Area",
        "Bar",
        "Waiter Service",
        "Self-Service",
        "Air Conditioning",
        "Heating",
        "Play Area",
        "Special Events",
        "Catering",
        "Gift Cards",
        "Online Ordering",
        "Contactless Payment",
        "Elderly Friendly",
        "Group Dining",
        "Private Rooms",
        "Alcohol",
        "Non-Alcoholic Beverages",
        "Vegetarian Options",
        "Vegan Options",
        "Gluten-Free Options",
        "Halal Options",
        "Kosher Options",
        "Nut-Free Options",
        "Dietary Restrictions",
        "Language Services"
    ],
    foodCategories: [
        "Starters",
        "Main Course",
        "Biryani & Rice",
        "Indian Breads",
        "Curries & Gravies",
        "Snacks",
        "Breakfast",
        "Desserts",
        "Salads",
        "Soups",
        "Chinese",
        "South Indian",
        "North Indian",
        "Fast Food",
        "Burgers",
        "Pizzas",
        "Wraps & Rolls",
        "Sandwiches",
        "Beverages",
        "Milkshakes",
        "Mocktails",
        "Ice Creams",
        "Combos & Thalis",
        "Tandoori",
        "Seafood Specials",
        "Egg Specials",
        "Veg Specials",
        "Non-Veg Specials"
    ]

};

export default Databank;

